//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_lehoanglong_2210900037.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebWuwaEntities : DbContext
    {
        public WebWuwaEntities()
            : base("name=WebWuwaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<danhgia> danhgias { get; set; }
        public virtual DbSet<Sukien> Sukiens { get; set; }
        public virtual DbSet<thamgia> thamgias { get; set; }
        public virtual DbSet<thongtinUser> thongtinUsers { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
