//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_lehoanglong_2210900037.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sukien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sukien()
        {
            this.thamgias = new HashSet<thamgia>();
        }
    
        public int ev_id { get; set; }
        public string tieude { get; set; }
        public string noidung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<thamgia> thamgias { get; set; }
    }
}
