//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_lehoanglong_2210900037.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thongtinUser
    {
        public int tt_id { get; set; }
        public int user_id { get; set; }
        public string fullname { get; set; }
        public string avatar { get; set; }
        public string tieusu { get; set; }
    
        public virtual User User { get; set; }
    }
}
